name: "feishu info"
on: push
jobs:
  RSS_Process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: 安装依赖
        run: yarn install
      - name: 执行RSS程序
        run: yarn rss
        env:
          HEHE: 333222111
          SEED_URL: ${{ secrets.SEED_URL }}
          WEB_HOOK: ${{ secrets.WEB_HOOK }}
      - name: commit code
        run: |
          git add .
          export COMMIT_DATE=$(date)
          git config --local user.email "robot@robot.kasong.com"
          git config --local user.name "feishu-robot-github-actions"
          git commit -m "定时执行 $COMMIT_DATE"
      - name: push code
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true
