name: "feishu send infro"
on:
  schedule:
    - cron: "0 */10 * * *"
jobs:
  RSS_Process:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: 同步环境变量
        run: |
          touch .env
          echo SEED_URL=${{ secrets.SEED_URL }} >> .env
          echo WEB_HOOK=${{ secrets.WEB_HOOK }} >> .env
          npm run syncENV
      - name: 安装依赖
        run: npm install
      - name: 执行RSS程序
        run: npm run rss
      - name: 提交代码
        run: git add .
        run: export COMMIT_DATE=$(date)
        run: git commit -m "定时执行 $COMMIT_DATE"
        run: git push origin master
